name: Speed Comparison

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-time-benchmarks:
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Pull Requests' }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        class: [BasicTests, DataDrivenTests, SetupTeardownTests, AsyncTests, FixtureTests, ParallelTests, AssertionTests, RepeatTests]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    concurrency:
      group: "speed-comparison-run-time-${{matrix.os}}-${{matrix.class}}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Build All Frameworks
        run: |
          dotnet build -c Release -p:TestFramework=TUNIT
          dotnet build -c Release -p:TestFramework=XUNIT
          dotnet build -c Release -p:TestFramework=NUNIT
          dotnet build -c Release -p:TestFramework=MSTEST
        working-directory: "tools/speed-comparison/UnifiedTests"

      - name: Run Benchmark
        run: dotnet run -c Release --framework net9.0 --allCategories=Runtime
        working-directory: "tools/speed-comparison/Tests.Benchmark"
        env:
          CLASS_NAME: ${{ matrix.class }}

      - name: Upload Markdown
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.os }}_markdown_run_time_${{ matrix.class }}
          path: |
            **/BenchmarkDotNet.Artifacts/**


  build-time-benchmarks:
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Pull Requests' }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # framework: [net8.0, net9.0]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    concurrency:
      group: "speed-comparison-build-time-${{matrix.os}}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Prepare builds
        run: |
          dotnet restore UnifiedTests/UnifiedTests.csproj
        working-directory: "tools/speed-comparison"

      - name: Run Benchmark
        run: dotnet run -c Release --allCategories=Build --framework net9.0
        working-directory: "tools/speed-comparison/Tests.Benchmark"

      - name: Upload Markdown
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.os }}_markdown_build_time
          path: |
            **/BenchmarkDotNet.Artifacts/**
